### ISSUE TITLE
Mobile Version (Later)

### ISSUE THREAD

**Issue by RichCherng** [BeachHacks/Beach_Live#24]

**Comment by jaylenw** [comment]
i think if you want to make the website mobile friendly, we should do so sooner than later. It could be more difficult to make it mobile friendly later down the road.

This is pretty much what it looks like on my phone as well.

![screenshot from 2017-03-11 00-32-07](https://cloud.githubusercontent.com/assets/6505395/23821806/8b0d7ffc-05f2-11e7-929c-ce590ec869cc.png)

**Comment by RichCherng** [comment]
Ill get on it, i might have a plan for this but it could be total whack too haha.
