### ISSUE TITLE
Api Key

### ISSUE THREAD

**Issue by alekskivuls** [BeachHacks/Beach_Live#31]
May be possible to hide API key since we are using Firebase as the server. Look into it.

**Comment by RichCherng** [comment]
http://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public

![ss 2017-02-22 at 07 40 39](https://cloud.githubusercontent.com/assets/5782659/23243929/dd72261c-f936-11e6-9029-7c564b097d32.png)
