### ISSUE TITLE
Venue Map

### ISSUE THREAD

**Issue by alekskivuls** [BeachHacks/Beach_Live#80]
Add a venue map tab using USU map as base image.
http://www.asicsulb.org/corporate/resources/usu-directory
I (@alekskivuls) can modify the image later once it's in the tab.

**Comment by RichCherng** [comment]
@jaylenw Can you add a tab on Map page and work with Aleks on this. I won't be home till night.

**Comment by jaylenw** [comment]
@RichCherng i work on it right now
