### ISSUE TITLE
Correct Spelling errors on schedule

### ISSUE THREAD

**Issue by jaylenw** [BeachHacks/Beach_Live#85]
just a note. I currently dont have password to the site to make necessary corrections.

"cup" and "registration"

![screenshot from 2017-04-21 01-39-32](https://cloud.githubusercontent.com/assets/6505395/25269912/818c02ee-2633-11e7-834d-986bb086b76d.png)

**Comment by RichCherng** [comment]
@jaylenw Same password as always, check slack for how to log in. FYI, the password will be changed soon.
